FeatureRequestProject/FeatureRequestProject/urls.py
from django.conf.urls import url
from django.contrib import admin
import feature_request.views

urlpatterns = [
    url(r'^$', feature_request.views.home),
    url(r'^feature_request/', feature_request.views.feature_request),
    url(r'^view_requests/', feature_request.views.view_requests),
    url(r'^admin/', admin.site.urls),
]

FeatureRequestProject/feature_request/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class FeatureRequest(models.Model):
    # Available clients used in model
    CLIENTS = (
        (1, 'Client A'),
        (2, 'Client B'),
        (3, 'Client C'),
    )
    # Available product areas used in model
    PRODUCT_AREAS = (
        (1, 'Policies'),
        (2, 'Billing'),
        (3, 'Claims'),
        (4, 'Reports'),
    )
    title = models.CharField(max_length=120)
    description = models.CharField(max_length=2048)
    client = models.IntegerField(choices=CLIENTS)
    client_priority = models.IntegerField()
    target_date = models.DateField()
    ticket_url = models.CharField(max_length=2048)
    product_area = models.IntegerField(choices=PRODUCT_AREAS)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)

FeatureRequestProject/feature_request/forms.py
from django import forms
from django.forms.widgets import DateInput, NumberInput, URLInput
from .models import FeatureRequest
from datetime import datetime

class FeatureRequestForm(forms.ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ('title','description','client','client_priority',\
                  'target_date', 'ticket_url', 'product_area')
        # Select widgets for certain fields
        widgets = {
            'description':forms.Textarea(attrs={'rows':'4'}),
            'client_priority':NumberInput(attrs={'min': '1'}),
            'target_date':DateInput(attrs = {'type':'date'}),
            'ticket_url':URLInput(),
        }

    def clean_target_date(self):
        """ Checks if the given target date is in the future """
        date_given = self.cleaned_data.get('target_date')
        if date_given < datetime.today().date():
            raise forms.ValidationError("Please select a future target date.")
        return date_given

FeatureRequestProject/feature_request/views.py
from django.shortcuts import render
from .forms import FeatureRequestForm
from .models import FeatureRequest

def view_requests(request):
    """ Renders view that diplays all feature requests
    Args: 
        request: http get request from user
    Returns: 
        rendered html page with requests
    """
    
    title = "Feature Requests"
    feature_requests = FeatureRequest.objects.all().order_by('client_priority')
    context = {
        "template_title": title,
        "feature_requests": feature_requests,
    }
    return render(request, "view_requests.html", context)

def home(request):
    """ Renders view for application home page
    Args: 
	request: http get request from user
    Returns: 
        rendered html home page
    """

    title = "Welcome to Feature Request"
    context = {
        "template_title": title,
    }
    return render(request, "home.html", context)

def update_priorities(current_priority, client_name):
    """ Updates client priorities to priority + 1 if a record with
        the same client name and priority exist.
    Args:
	current_priority: priority to check for existing record
        client_name: name of client to check for existing record
    Returns:
	None
    """
    try:
        # check if there is a client with the same priority in records
        priority_exists = FeatureRequest.objects.get(client=client_name, \
						     client_priority=current_priority)
        # If there is, check if there is for the next priority
        current_priority += 1
        update_priorities(current_priority, client_name)
        # Now update current record with updated priority
        priority_exists.client_priority = current_priority
        priority_exists.save()
    except FeatureRequest.DoesNotExist:
        # No other records in the way
        return

def feature_request(request):
    """ Renders view for feature request page
    Args:
	request: http get request from user
    Returns:
        rendered html feature request page with request form
    """

    title = "Feature Request"
    form = FeatureRequestForm(request.POST or None)
    
    if form.is_valid():
        # Get the client and priority to check for existing records
        provided_client = form.cleaned_data.get("client")
        provided_priority = form.cleaned_data.get("client_priority")
        # Move records with same client and priority back
        update_priorities(provided_priority, provided_client)
        form.save()
        return view_requests(request)
	
    context = {
        "template_title": title,
        "feature_form": form,
    }
    return render(request, "feature_request.html", context)

FeatureRequestProject/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Base template for Feature Request App">
    <meta name="author" content="mrandersondev">

    <title> {{ template_title }} </title>

    {% include 'head_css.html' %}

  </head>

  <body>

    {% include 'navbar.html' %}

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="inner-content">

            {% block content %}

            {% endblock %}

          </div>

        </div>

        {% include 'footer.html' %}

      </div>

    </div>

    {% include 'javascript.html' %}

  </body>
</html>

FeatureRequestProject/templates/feature_request.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="inner cover">
  <h1 class="cover-heading">Feature Request</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <form method='POST' action=''>{% csrf_token %}
      {{ feature_form|crispy }}
      <input class="btn btn-primary" type='submit' value='Request'>
    </div>
  </div>
</div>
{% endblock %}

FeatureRequestProject/templates/footer.html
<footer class="footer">
      <div class="container">
        <p>Template by <a href="https://twitter.com/mdo">@mdo</a>
         | App by <a href="https://github.com/mrandersondev">mrandersondev</a></p>
      </div>
</footer>

FeatureRequestProject/templates/head_css.html
{% load staticfiles %}
<!-- Bootstrap core CSS -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static 'feature_request/css/base.css' %}" rel="stylesheet">

FeatureRequestProject/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="inner cover">
  <h1 class="cover-heading">Feature Request</h1>
  <p class="lead">Enter a new feature request using the most advanced feature request system available.</p>
  <p class="lead">
    <a href="/feature_request" class="btn btn-lg btn-default">Get Started</a>
  </p>
</div>
{% endblock %}

FeatureRequestProject/templates/javascript.html
<!-- Bootstrap core JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

FeatureRequestProject/templates/navbar.html
    <nav class="navbar navbar-masthead navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href='/'>IWS Feature Request System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
	    <li class="active"><a href="/">Home</a></li>
            <li><a href="/feature_request">Feature Request</a></li>
            <li><a href="/view_requests">Requests</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

FeatureRequestProject/templates/view_requests.html
{% extends "base.html" %}
{% block content %}
<div class="inner cover">
  <h1 class="cover-heading">All Feature Requests</h1>
  <div class="row">
  {% if feature_requests %}
    <table class='table table-bordered'>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Client</th>
        <th>Client Priority</th>
        <th>Target Date</th>
        <th>Ticket Url</th>
        <th>Product Area</th>
        <th>Date Created</th>
      </tr>
      {% for request in feature_requests %}
        <tr>
          <td>{{ request.title }}</td><td>{{ request.description }}</td><td>{{ request.get_client_display }}</td><td>{{ request.client_priority }}</td><td>{{ request.target_date }}</td><td>{{ request.ticket_url }}</td><td>{{ request.get_product_area_display }}</td><td>{{ request.date_created }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
  </div>
</div>
{% endblock %}